# Generated by Django 3.2.14 on 2022-08-22 16:34

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0019_add_customer_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_amount_decimal',
            field=djstripe.fields.StripeDecimalCurrencyAmountField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
    ]
